### ISSUE TITLE
How to get waybar effect showed in screenshot?

### ISSUE THREAD

**Issue by Sprite36** [tim3dman/.dotfiles#1]
https://github.com/tim3dman/.dotfiles/blob/main/Screenshots/screenshot_2021-11-15_22-25-02_641878534.png 
It shows a pixelated sidebar but I didn't found the dotfile.

**Comment by tim3dman** [comment]
Hi the little pixel ends is a nerd font icon SymbolsNerdFontComplete, just make sure you have it installed.
